databases:
  - name: devtestdb
    plan: free
    databaseName: devtest
    user: devtest

services:
  - type: web
    plan: free
    name: devtest
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn DevTest.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: devtestdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4